services:
  db:
    image: postgres:17
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_DB: repair_log
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
